// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalkStream_API.Database;

#nullable disable

namespace TalkStream_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240709110742_Refresh")]
    partial class Refresh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TalkStream_API.Entities.FriendRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AddresseeId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("AddresseeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasColumnType("varchar(36)");

                    b.Property<string>("RequesterName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AddresseeId");

                    b.HasIndex("RequesterId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("TalkStream_API.Entities.User", b =>
                {
                    b.Property<string>("Uid")
                        .HasMaxLength(36)
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("varchar(120)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserUid")
                        .HasColumnType("varchar(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Uid");

                    b.HasIndex("UserUid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TalkStream_API.Entities.FriendRequest", b =>
                {
                    b.HasOne("TalkStream_API.Entities.User", "Addressee")
                        .WithMany("ReceivedFriendRequests")
                        .HasForeignKey("AddresseeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TalkStream_API.Entities.User", "Requester")
                        .WithMany("SentFriendRequests")
                        .HasForeignKey("RequesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addressee");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("TalkStream_API.Entities.User", b =>
                {
                    b.HasOne("TalkStream_API.Entities.User", null)
                        .WithMany("Friends")
                        .HasForeignKey("UserUid");
                });

            modelBuilder.Entity("TalkStream_API.Entities.User", b =>
                {
                    b.Navigation("Friends");

                    b.Navigation("ReceivedFriendRequests");

                    b.Navigation("SentFriendRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
